### ISSUE TITLE
Generalized gradient approximation for grid_field maps

### ISSUE THREAD

**Issue by eiad-hamwi** [bmad-sim/bmad_distribution#2]
It would be useful to implement a generalized gradient approximation for grid field maps in order to calculate higher-order taylor maps of these elements. 

Furthermore, implementing a simple scaling functionality for the overall field strength would be convenient for a basic parametrization of the lattice element in question.

**Comment by DavidSagan** [comment]
@eiad-hamwi Sorry some confusion here. Active issue list is at https://github.com/DavidSagan/Bmad/issues. Could you please open this issue there? Thanks.

**Comment by eiad-hamwi** [comment]
sorry for the confusion, thanks for letting me know!
