### ISSUE TITLE
Custom shape pattern not found

### ISSUE THREAD

**Issue by kdeitrick** [bmad-sim/bmad_distribution#3]
[buggy_shape.zip](https://github.com/bmad-sim/bmad_distribution/files/11170943/buggy_shape.zip)

Running update from 20230404, when setup runs, get the error "pattern:q_pat DOES NOT HAVE AN ASSOCIATED PATTERN. IN NAMELIST: FLOOR_PLAN_DRAWING"

Example taken from 10.13.9 in tao manual.

**Comment by DavidSagan** [comment]
Fixed. Custom patterns was never fully implemented.
